### PR TITLE
I was getting an odd error when trying to load anything (check http://oi5

### PR DESCRIPTION
**Pull request by dariocravero**
I was getting an odd error when trying to load anything (check http://oi52.tinypic.com/2d7g9r6.jpg -strangely the error appears like an image :S!!).

Still, change the require to require 'sprockets' or adding sprockets/version (like the change I'm proposing here) works fine.

Is there a particular reason why you aren't requiring the whole library?

By the way, I've setup my app in the simplest way (as you specify on the docs).
Cheers!

### CODE REVIEW

**Comment by vic** [comment]
+1 on merging this, I was getting the same error

```
`const_missing': uninitialized constant Sprockets::Base::Paths (NameError)
    from /Users/vic/.rvm/gems/ruby-1.9.3-p125/gems/sprockets-2.4.0/lib/sprockets/base.rb:13:in `<class:Base>'
    from /Users/vic/.rvm/gems/ruby-1.9.3-p125/bundler/gems/padrino-sprockets-9bf57c1fe1b0/lib/padrino/sprockets.rb:2:in `require'
```

I solved it by modifying the `lib/padrino/sprockets.rb` file to require `sprockets` instead of `sprockets/environment`, it seems `sprockets.rb` by itself will install all the autoloads needed for it to function so I'd say the offending line should read:

``` ruby
require 'sprockets'
```

FYI @nightsailer .. this issue looks like 6-months old, but it seems the error is still present on the padrino-sprockets i'm using from this repo master branch.

**Comment by gilbert** [comment]
+1. For the record, I'm getting the same error (new project, so latest version of everything):

```
`const_missing': uninitialized constant Sprockets::Base::Paths (NameError)
    from /Users/tapwater/.rvm/gems/ruby-1.9.2-p318/gems/sprockets-2.4.0/lib/sprockets/base.rb:13:in `<class:Base>'
    from /Users/tapwater/.rvm/gems/ruby-1.9.2-p318/gems/sprockets-2.4.0/lib/sprockets/base.rb:12:in `<module:Sprockets>'
    from /Users/tapwater/.rvm/gems/ruby-1.9.2-p318/gems/sprockets-2.4.0/lib/sprockets/base.rb:10:in `<top (required)>'
```

**Comment by elianderson** [comment]
I doesn't look like this was merged in, I am seeing this issue on a fresh project, anyone find a resolution?

**Comment by vic** [comment]
@nightsailer any reason this hasn't be merged into master?

**Comment by nightsailer** [comment]
@vic Sorry, my wrong, it can't be merged automatically. I just manual fix that.

**Comment by basex** [comment]
To have the problem easily solved, add to your Gemfile

```
gem 'padrino-sprockets', :require => ["sprockets","padrino/sprockets"], :git => 'git://github.com/nightsailer/padrino-sprockets.git'
```

**Comment by wikimatze** [comment]
@basex that was the solution to exact the same problem I run into. I somebody going to fix this, because the thing above looks terrible in the Gemfile.

**Comment by wikimatze** [comment]
The README is fixed now and code mentioned in the commits here is integrated in the gem.

**Pull request closed without merging**
